image: node:10

cache:
  paths:
    - node_modules/

before_script:
  - npm install

test:
  stage: test
  only:
    - master
  script:
    - npm run lint
    - npm test

deploy:
  stage: deploy
  only:
    - master
  script:
    - apt-get update -yq
    - apt-get install rubygems ruby-dev -y
    - gem install dpl
    - npm run build
    - cd .dist
    - dpl --provider=heroku --skip-cleanup --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
